#!/bin/sh

case "$1" in
	start)
		echo "Loading scull module" >> /var/log/aesdchar.log
		./usr/bin/aesdchar_load >> /var/log/aesdchar.log 2>&1
		;;
	stop)
		echo "Unloading scull module" >> /var/log/aesdchar.log
		./usr/bin/aesdchar_unload >> /var/log/aesdchar.log 2>&1
		;;
	*)
		echo "Usage: $0 {load|unload}"
		exit 1
esac
exit 0
